services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../envs/db.env
    networks:
      - work-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ../envs/api.env
      - ../envs/db.env
    depends_on:
      - postgres
    networks:
      - work-network

volumes:
  postgres_data:

networks:
  work-network:
    driver: bridge
